### ISSUE TITLE
Bugs: Group_summariser 

### ISSUE THREAD

**Issue by LuciaSegovia** [TomCodd/NutritionTools#4]
Hi @LuciaSegovia !

Sorry, thats definitely a problem - can you send me the dataset you were trying it with (i.e. save it as an R data file just before it was input into the Summariser) , and the group summariser command you were running? I'll see if I can sort it :)

_Originally posted by @TomCodd in https://github.com/TomCodd/NutritionTools/issues/2#issuecomment-1827595435_

**Comment by LuciaSegovia** [comment]
I think it's better to take this into a separate thread, as the other should be for new functions ideas 😅

**Comment by TomCodd** [comment]
Yeah, definitely haha :)

**Comment by TomCodd** [comment]
Hi @LuciaSegovia  - This should now be fixed :) The bug was that any errors were being attributed to the first group ID on the list (1001 in this case), but the error message was caused by a different group (1002) for a legitimate reason - the weightings total ~ 0.75 :) 

Please can you reinstall and make sure thats now working for you? :)

**Comment by LuciaSegovia** [comment]
Thank you @TomCodd ! It run perfectly on my side :) . Although I found another issue. See in the picture attached, that the id is missing in the summary row. I think this will cause problems down the line. 

![image](https://github.com/TomCodd/NutritionTools/assets/48588417/8bcb7428-cfa0-4495-88a2-c284e70796ea)

**Comment by TomCodd** [comment]
Hi @LuciaSegovia !

Hmmm - missing the item_desc you mean?

**Comment by LuciaSegovia** [comment]
Sorry @TomCodd! What I meant is if you check row 5 and row 7, it should say "SUMMARY ROW - 1002" and "SUMMARY ROW - 1004" respectively, instead of "SUMMARY  ROW - NA".

**Comment by TomCodd** [comment]
Thats ok @LuciaSegovia !

Ah, ok - I see what you mean. I'll look into it now :) Theres also the row order I want to double check. Did you make any other changes to that dataset since you sent it to me, aside from adding pork lard?

**Comment by LuciaSegovia** [comment]
Thank you @TomCodd!

I am doing some changes to the dataset, but they should be irrelevant to the summariser.

**Comment by TomCodd** [comment]
No problem @LuciaSegovia , thank you for finding them!

I've solved that problem - give it a minute for the website to update and please could you try installing the package again, and see if its working for you too? :)

**Comment by LuciaSegovia** [comment]
@TomCodd it's not working for me :(

**Comment by TomCodd** [comment]
@LuciaSegovia  :( 

Apparently the push didn't work lol - sorry! Give it a minute or two, reinstall and try again? :)

**Comment by LuciaSegovia** [comment]
Thank you @TomCodd !! It's working!! YAY!

**Comment by TomCodd** [comment]
@LuciaSegovia Glad its working!! :)
